version: '2'
services:
    client-dev:
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        depends_on:
            - api-dev
        environment: 
            - CHOKIDAR_USEPOLLING=true
        stdin_open: true
    api-dev:
        build: ./src/api
        ports:
            - '3999:3999'
